---
title: "Dashboard for SO questions in Rmarkdown Cookbook"
output: 
  flexdashboard::flex_dashboard:
    self_contained: false
    orientation: rows 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(polite)
library(rvest)
library(purrr)
# control what evaluate or not in dev mode
is_dev <- as.logical(Sys.getenv("IS_DEV", FALSE))
message(ifelse(is_dev, "DEV MODE ON", "DEV MODE OFF")) 
```

```{r parsing-so, eval = FALSE}
# Get Top 500 SO questions
## scrape website
# we want to retrieve the 500 top question
so_url <- "https://stackoverflow.com/questions/tagged/r-markdown"
session <- bow(so_url)
top <- 500
result_per_page <- 50
nb_page <- ceiling(top / 50)
# nb_page <- 1
res <- seq_len(nb_page) %>%
  map(~ scrape(session, 
               params = glue::glue("page={page_nb}&sort=votes&pagesize={result_per_page}", 
                                   page_nb = .x), verbose = TRUE
  ))
```

```{r get-so-qa-url, eval = FALSE}
## get question url
so_top_qa <- res %>%
  map(~html_nodes(.x, "h3 >a.question-hyperlink") %>%
        html_attr("href") %>%
        map_chr(~ httr::modify_url(so_url, path = .x))) %>%
  flatten_chr() %>%
  tibble(urls = .) %>%
  mutate(
    top = row_number(),
    id = str_extract(urls, "(?<=/)\\d{8}(?=/)") 
  )
readr::write_csv("TOP500_QA_SO.csv")
```

```{r parsing-most-viewed}
# Exported from 
# https://data.stackexchange.com/stackoverflow/query/341524/most-viewed-questions-in-tag#resultSets
# on 22/10/2018
most_viewed <- read_csv("MOST_VIEWED_QA_SO.csv", 
    col_types = cols(`Post Link` = col_character())) %>%
  arrange(desc(ViewCount)) %>%
  rename(id = `Post Link`) %>%
  mutate(most_viewed = row_number())
```

```{r get-so-in-gh, eval = TRUE}
# helpers
get_so_id <- function(so_url) {
  str_extract(so_url, "(?<=questions/)\\d{8}(?=/.*)")
}
# REM : NOT RUN IN DEV MODE (if IS_DEV env var is true)
# Find QA already looked at on GH
# Use github graphQL API
if (!is_dev){
  library(ghrecipes)
  owner <- "dr-harper"
  repo <- "rmarkdown-cookbook"
  ignored_issues <- c(4)
  issues <- get_issue_labels_state(owner, repo)
  get_all_thread <- map_dfr(issues$number, ~ get_issue_thread(owner, repo, .x))
  so_in_gh <- get_all_thread %>%
    # do not select some issue
    filter(!issue %in% ignored_issues) %>%
    # get only issues with stackoverflow url
    mutate(has_so_url = str_detect(body, "https://stackoverflow.com")) %>%
    filter(has_so_url) %>%
    mutate(so_url = str_extract_all(body, "\\bhttps://stackoverflow.com/[^\\s)]*")) %>%
    unnest(so_url) %>%
    # deal with comment shared url
    mutate(so_url = map_if(so_url, 
                           ~str_detect(.x, "https://stackoverflow.com/a/.*"), 
                           ~httr::GET(.x)$url) %>% flatten_chr,
           id = get_so_id(so_url)) %>%
    # Add status
    mutate(status = if_else(grepl("^9999-01-01$", closed_at), "OPENED", "CLOSED")) %>%
    select(issue, status, so_url_gh = so_url, id) %>%
    distinct()
}
```
  
```{r rds-for-dev, eval = FALSE}
# saved once for dev purposes
saveRDS(so_in_gh, "so_in_gh.rds")
```

```{r load-dev-table, eval = TRUE}
# only run if IS_DEV env var is TRUE
# Purpose : Prevent github api request in dev mode
if (is_dev) {
  so_in_gh <- readRDS("so_in_gh.rds")
}
```


```{r data-top-500-in-gh}
# summary of already dealt issues
top_QA <- read_csv("TOP500_QA_SO.csv", col_types = "cic")
ignored_qa <- gistr::gist("https://gist.github.com/cderv/76728b02c13e429c843cc8b3b7226f11") %>%
  purrr::pluck("files", "ignored_qa.txt", "raw_url") %>%
  readr::read_tsv(col_names = "so_url", col_types = "c") %>%
  dplyr::mutate(id = get_so_id(so_url))
full_table <- so_in_gh %>%
  # add top QA
  full_join(top_QA, by = "id") %>%
  # add most viewed already Top QA
  left_join(most_viewed %>% select(id, ViewCount, most_viewed), by = "id") %>%
  # add most 500 viewed not already in
  full_join(most_viewed %>% select(id, ViewCount, most_viewed) %>% filter(most_viewed <= 500)) %>%
  select(top, urls, id, issue, status, most_viewed, ViewCount) %>%
  arrange(top, most_viewed) %>%
  mutate(
    # build url for SO questions not in the top 500
    urls = if_else(is.na(urls), paste0("https://stackoverflow.com/questions/", id), urls),
    # create link
    urls = map_chr(urls, ~htmltools::a(.x, href = .x, target="_blank") %>% as.character),
    # create link toward issue
    issue_link = map_chr(
      issue, 
      ~htmltools::a(.x,
                    href = paste0("https://github.com/dr-harper/rmarkdown-cookbook/issues/", .x),
                    target="_blank") %>%
        as.character()),
    ignored = id %in% ignored_qa$id 
  )
```


Dashboard
===========================

Updated: `r Sys.time()`

Row
----------------------------------------

### Nb of questions in closed GH ticket

```{r}
closed_rate <- full_table %>% 
  filter(!is.na(issue)) %>% 
  distinct(id, .keep_all = TRUE) %>%
  group_by(id) %>% 
  summarise(CLOSED = all(status == "CLOSED")) %>% 
  count(CLOSED)
flexdashboard::gauge(closed_rate %>% filter(CLOSED == TRUE) %>% pull(n),
                     0, 
                     sum(closed_rate$n))
```


### Achievement of the top 500 report in SO

```{r achievement-gauge}
rate <- full_table %>% 
  distinct(id, .keep_all = TRUE) %>%
  filter(!is.na(top)) %>%
  # an ignored sa is count as treated
  count(ok = !is.na(issue) | ignored) %>% 
  filter(ok) %>% 
  pull(n)
flexdashboard::gauge(rate, 0, 
                     full_table %>% 
                       filter(!is.na(top)) %>%
                       distinct(id) %>%
                       count() %>%
                       pull(n))
```

### Achievement of the top 500 MOST VIEWED

```{r achievement-gauge}
rate <- full_table %>% 
  distinct(id, .keep_all = TRUE) %>%
  filter(!is.na(most_viewed)) %>%
  # an ignored sa is count as treated
  count(ok = !is.na(issue) | ignored) %>% 
  filter(ok) %>% 
  pull(n)
flexdashboard::gauge(rate, 0, 
                     full_table %>% 
                       filter(!is.na(most_viewed)) %>%
                       distinct(id) %>%
                       count() %>%
                       pull(n))
```

### Nb of SO questions reported not in either Tops)

```{r all-so}
flexdashboard::valueBox(
  full_table %>% filter(is.na(top) & is.na(most_viewed)) %>% count() %>% pull(n),
  caption = "Number of SO QA not in TOP or most viewed"
)
```

### Nb of ignored questions

```{r ignored-so}
flexdashboard::valueBox(
  nrow(ignored_qa),
  caption = "Number of ignored QA from TOP 500, not reported in GH"
)
```


Row
---------------------------

### SO QA in GH

```{r barplot-done}
full_table %>%
  distinct(id, .keep_all = TRUE) %>%
  mutate(not_in_gh = if_else(is.na(issue), "not in GH yet", "Already in GH")) %>%
  ggplot(aes(not_in_gh, fill = not_in_gh)) +
  geom_bar(position = "dodge") +
  geom_text(aes(label = stat(count), y = stat(count)), stat = "count", vjust = -0.5, hjust = 0.5) +
  theme_light() +
  scale_x_discrete(breaks = NULL) +
  labs(
    title = "Nb of SO questions in GH issues",
    x = NULL,
    fill = "Top SO QA"
  )
```


### Next Questions

```{r left-questions}
full_table %>%
  filter(is.na(issue) & !ignored) %>%
  select(top, urls) %>%
  arrange(top) %>%
  DT::datatable(escape = FALSE)
```


Data 
============================

Row {.tabset .tabset-fade}
-------------------------------------------

```{r dt-wrapper, include = FALSE}
data_table <- function(tab, ...) {
  DT::datatable(tab,
                escape = FALSE, 
                filter = "top")
}
```


### All SO questions mentionned in GH issues 

This table contains TOP 500 QA from SO and where they are mentionned in issues

```{r render-full-table}
data_table(full_table %>% 
             filter(!is.na(issue)) %>%
             select(-issue) %>%
             # put top = 0 for non top 500 SO QA
             mutate(top = if_else(is.na(top), 0L, top)) %>%
             filter(!ignored),
           options = list(
             columnDefs = list(list(className = 'dt-center', targets = 0:4))
           ))
```

### Ignored SO QA

```{r ignored_qa}
data_table(full_table %>%
                semi_join(ignored_qa, by = "id") %>%
                select(top, urls, id), 
)
```


